refactor(github): useless

diff --git a/.github/workflows/reusable-ios-testflight-publish.yaml b/.github/workflows/reusable-ios-testflight-publish.yaml
--- a/.github/workflows/reusable-ios-testflight-publish.yaml
+++ b/.github/workflows/reusable-ios-testflight-publish.yaml
@@ -71,94 +71,94 @@ jobs:
       - name: Import iOS certificate (.p12)
         run: |
           echo "${{ secrets.IOS_CERTIFICATE_P12 }}" | base64 --decode > ios_certificate.p12
-          security import ios_certificate.p12 -k ~/Library/Keychains/build.keychain -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
-
-      # Install the provisioning profile
-      - name: Install provisioning profile
-        run: |
-          echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/YourProvisioningProfile.mobileprovision
-
-      # Pod install
-      - name: Pod install
-        run: |
-          pod cache clean --all
-          rm -rf Pods
-          rm Podfile.lock
-          pod install
-
-      # Build IPA
-      - name: Build IPA
-        run: |
-          if [ ! -f "${{ inputs.xcworkspace }}" ] && [ ! -d "${{ inputs.xcworkspace }}" ]; then
-            echo "Workspace file not found!"
-            exit 1
-          fi
-
-          if [ ! -f "${{ inputs.export_options_plist }}" ] && [ ! -d "${{ inputs.export_options_plist }}" ]; then
-            echo "ExportOptions.plist file not found!"
-            exit 1
-          fi
-
-          xcodebuild -workspace ${{ inputs.xcworkspace }} \
-            -scheme ${{ inputs.scheme }} \
-            -sdk iphoneos \
-            -configuration AppStoreDistribution \
-            -allowProvisioningUpdates \
-            -archivePath $PWD/build/App.xcarchive
-
-          xcodebuild -exportArchive \
-            -archivePath $PWD/build/App.xcarchive \
-            -exportPath $PWD/build \
-            -exportOptionsPlist ${{ inputs.export_options_plist }} \
-            -allowProvisioningUpdates
-
-      # Upload IPA build to TestFlight
-      - name: Upload to TestFlight
-        env:
-          API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
-          ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
-        run: |
-          if [ ! -f "${{ inputs.ipa_file }}" ]; then
-            echo "IPA file not found!"
-            exit 1
-          fi
-
-          xcrun altool --list-providers \
-            --apiKey $API_KEY_ID \
-            --apiIssuer $ISSUER_ID
-
-      # Increment version
-      - name: Bump version
-        run: ./increment_version.sh
-        env:
-          PROPERTIES_FILE: ${{ inputs.PROPERTIES_FILE }}
-
-      # Retrieve new version
-      - name: Retrieve new version
-        id: versionName
-        run: |
-          if [ ! -f "${{ inputs.PROPERTIES_FILE }}" ]; then
-            echo "Properties file not found!"
-            exit 1
-          fi
-
-          version=$(grep "VERSION_NAME=" ${{ inputs.PROPERTIES_FILE }} | cut -d'=' -f2)
-          if [ -z "$version" ]; then
-            echo "Version not found in properties file!"
-            exit 1
-          fi
-
-          echo "versionName=$version" >> $GITHUB_ENV
-          echo "versionName=$version" >> $GITHUB_OUTPUT
-
-      # Commit version changes
-      - name: Commit version changes
-        id: committer
-        uses: planetscale/ghcommit-action@v0.1.6
-        env:
-          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
-        with:
-          repo: ${{ github.repository }}
-          branch: master
-          commit_message: "chore: bump version to ${{ steps.versionName.outputs.versionName }}"
-          file_pattern: ${{ inputs.PROPERTIES_FILE }}
+      #     security import ios_certificate.p12 -k ~/Library/Keychains/build.keychain -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
+      #
+      # # Install the provisioning profile
+      # - name: Install provisioning profile
+      #   run: |
+      #     echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/YourProvisioningProfile.mobileprovision
+      #
+      # # Pod install
+      # - name: Pod install
+      #   run: |
+      #     pod cache clean --all
+      #     rm -rf Pods
+      #     rm Podfile.lock
+      #     pod install
+      #
+      # # Build IPA
+      # - name: Build IPA
+      #   run: |
+      #     if [ ! -f "${{ inputs.xcworkspace }}" ] && [ ! -d "${{ inputs.xcworkspace }}" ]; then
+      #       echo "Workspace file not found!"
+      #       exit 1
+      #     fi
+      #
+      #     if [ ! -f "${{ inputs.export_options_plist }}" ] && [ ! -d "${{ inputs.export_options_plist }}" ]; then
+      #       echo "ExportOptions.plist file not found!"
+      #       exit 1
+      #     fi
+      #
+      #     xcodebuild -workspace ${{ inputs.xcworkspace }} \
+      #       -scheme ${{ inputs.scheme }} \
+      #       -sdk iphoneos \
+      #       -configuration AppStoreDistribution \
+      #       -allowProvisioningUpdates \
+      #       -archivePath $PWD/build/App.xcarchive
+      #
+      #     xcodebuild -exportArchive \
+      #       -archivePath $PWD/build/App.xcarchive \
+      #       -exportPath $PWD/build \
+      #       -exportOptionsPlist ${{ inputs.export_options_plist }} \
+      #       -allowProvisioningUpdates
+      #
+      # # Upload IPA build to TestFlight
+      # - name: Upload to TestFlight
+      #   env:
+      #     API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
+      #     ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
+      #   run: |
+      #     if [ ! -f "${{ inputs.ipa_file }}" ]; then
+      #       echo "IPA file not found!"
+      #       exit 1
+      #     fi
+      #
+      #     xcrun altool --list-providers \
+      #       --apiKey $API_KEY_ID \
+      #       --apiIssuer $ISSUER_ID
+      #
+      # # Increment version
+      # - name: Bump version
+      #   run: ./increment_version.sh
+      #   env:
+      #     PROPERTIES_FILE: ${{ inputs.PROPERTIES_FILE }}
+      #
+      # # Retrieve new version
+      # - name: Retrieve new version
+      #   id: versionName
+      #   run: |
+      #     if [ ! -f "${{ inputs.PROPERTIES_FILE }}" ]; then
+      #       echo "Properties file not found!"
+      #       exit 1
+      #     fi
+      #
+      #     version=$(grep "VERSION_NAME=" ${{ inputs.PROPERTIES_FILE }} | cut -d'=' -f2)
+      #     if [ -z "$version" ]; then
+      #       echo "Version not found in properties file!"
+      #       exit 1
+      #     fi
+      #
+      #     echo "versionName=$version" >> $GITHUB_ENV
+      #     echo "versionName=$version" >> $GITHUB_OUTPUT
+      #
+      # # Commit version changes
+      # - name: Commit version changes
+      #   id: committer
+      #   uses: planetscale/ghcommit-action@v0.1.6
+      #   env:
+      #     GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
+      #   with:
+      #     repo: ${{ github.repository }}
+      #     branch: master
+      #     commit_message: "chore: bump version to ${{ steps.versionName.outputs.versionName }}"
+      #     file_pattern: ${{ inputs.PROPERTIES_FILE }}
